name: Code Scan (Detekt)

on:
  push:
    branches:
      [main]
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Detekt
        uses: natiginfo/action-detekt-all@1.22.0-RC1
        with:
          args: --build-upon-default-config --config=.github/config/detekt.yml
